### ISSUE TITLE
Connection 似乎是半双工的

### ISSUE THREAD

**Issue by Codesire-Deng** [Pang-GJ/luce#4]
似乎无法在两个协程中并发调用 connection::read/write，因为它们的在 epoll 中注册的是 coroutine_handle，这意味着同一时间在同一 fd 上最多只能关联一个 coroutine_handle。

如果对一个 socket 开两个协程，一个只 read，一个只 write，这似乎是不支持的。

**Comment by Pang-GJ** [comment]
分析了一下确实是有这个问题，当初没考虑到。

**Comment by Pang-GJ** [comment]
我想了一个fix方法：
```
class Socket {
// ....
// 增加一个Handle结构体
struct Handle {
... read_handle;
... write_handle;
};
Handle handle;
};

// 在epoll注册时
event.data.ptr = &socket.handle

// 之后epoll_wait返回时根据读还是写resume相应的handle
```
应该可以解决这个问题了
